### ISSUE TITLE
Events from Gridstack

### ISSUE THREAD

**Issue by Arerir** [aurelia-ui-toolkits/aurelia-gridstack#11]
Hi, is there any way to hook onto these events from Gridstack? We've tried by using delegate, trigger etc. but it doesn't seem to work 😄 
![image](https://user-images.githubusercontent.com/12257291/226359441-746735b9-ba82-4a02-8131-07d4d64ea9ab.png)

**Comment by MaximBalaganskiy** [comment]
Not at the moment, the grid does not dispatch those as html events.
You can create a custom attribute to propagate events `grid.on` or push PR here to support it natively
