### ISSUE TITLE
Error in handleChange with Undefined nodes on Aurelia-Gridstack v3.0.0 & v4.0.0

### ISSUE THREAD

**Issue by andreitaranu** [aurelia-ui-toolkits/aurelia-gridstack#12]
### Description
Encountering a runtime error in the `handleChange` method within `aurelia-gridstack`. The issue is observed both in version 3.0.0 and persists after updating to version 4.0.0. The error occurs when `handleChange` is triggered with an undefined or empty `nodes` parameter.

### Steps to Reproduce
1. Use `grid-stack` in an Aurelia component with bindable properties.
```html
<template>
    <grid-stack float options.bind="gridOptions" ref="gridStackEl">
        <grid-stack-item //someoptions>
            <input type="date" date.bind="fromDate">
        </grid-stack-item>
    </grid-stack>
</template>
```
2. Select a date and observe that changes in unrelated bindable properties seem to trigger `handleChange` in `grid-stack`.
![image](https://github.com/aurelia-ui-toolkits/aurelia-gridstack/assets/100191890/162c0e0a-a983-4177-8cde-7290513af8e8)
___
![image](https://github.com/aurelia-ui-toolkits/aurelia-gridstack/assets/100191890/47b9a74f-30e5-439a-a25c-0f79dbb7ea57)

### Expected Behavior
`handleChange` should not be triggered by changes in unrelated bindable properties, or it should be able to handle undefined `nodes` without throwing an error.

### Actual Behavior
`handleChange` is triggered with an undefined `nodes` parameter, resulting in a runtime error.

### Additional Context
The issue appears to be related to how Aurelia's binding system interacts with `grid-stack`. Removing certain bindings (e.g., `date.two-way="fromDate"`) prevents the error, suggesting a possible conflict in change detection or event handling.

### Environment
- Aurelia Framework Version: 1.4.1
- Aurelia-Gridstack Version: 4.0.0 (issue also present in 3.0.0)
- Browser: Chrome
- Language: TypeScript

Any insights or suggestions on this issue would be greatly appreciated.

**Comment by MaximBalaganskiy** [comment]
Looks like this issue belongs to the gridstack repository

**Comment by andreitaranu** [comment]
Thank you for the quick answer, I've reposted the issue on the gridstack repository, I guess this can be closed, if it's not relevant for the aurelia-gridstack repository.

**Comment by andreitaranu** [comment]
@MaximBalaganskiy The answer I've got in the gristack repository points out that the issue is more related to the aurelia-gridstack interactions, so it would be great if you could provide a bit of help with this 🙂
