### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by green3g** [aurelia-ui-toolkits/aurelia-gridstack#5]
Hi @MaximBalaganskiy  would you please be able to run a new release to npm with the updates?

**Comment by MaximBalaganskiy** [comment]
I’m on leave till 21st. Will release when get back

**Comment by MaximBalaganskiy** [comment]
Published v2 with upgraded gridstack

**Comment by green3g** [comment]
A week early! A new release on your holiday, thank you!
